### PR TITLE
updated list of uniforms

### PR DESCRIPTION
**Pull request by wurunduk**
updated existing uniforms to Include Iris
Added uniforms:
Blindness
Night Vision
Screen Brightness
Eye Altitude
Eye Brightness
Eye Brightness Smooth
Is Eye In Water
Wetness

### CODE REVIEW

**Review by coderbot16 — APPROVED** [review]
Thanks! The documentation for the additional uniforms is a bit sparse but it's possible to improve it separately. I'll look into it.

**Comment by coderbot16** [comment]
Hey @wurunduk would it be possible for you to confirm whether or not you're okay with your contribution being licensed under the LGPLv3 in https://github.com/IrisShaders/ShaderDoc/commit/82dac63d0545261cccd52548e89a1f9441604793 ? Thanks!

**Comment by wurunduk** [comment]
> 
> 
> Hey @wurunduk would it be possible for you to confirm whether or not you're okay with your contribution being licensed under the LGPLv3 in [82dac63](https://github.com/IrisShaders/ShaderDoc/commit/82dac63d0545261cccd52548e89a1f9441604793) ? Thanks!

Yeah, I'm okay with that

**Comment by coderbot16** [comment]
Great, thanks!

**Pull request merged**
